title: "記録"
description: "将棋・Chess・競技プログラミング・CS・プログラミングの記録"
author: "scripthropus"
email: "script2097152@gmail.com"

# GitHub Pages 設定
baseurl: "/blog"  # リポジトリ名
url: "https://scripthropus.github.io"  # GitHubユーザー名
domain: scripthropus.github.io  # HTTPS強制用

# Jekyll 設定
markdown: kramdown
highlighter: rouge
encoding: utf-8
timezone: Asia/Tokyo

# テーマ
theme: minima

# プラグイン (GitHub Pagesでサポートされているもののみ)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-archives  # GitHub Pagesではサポートされていないためコメントアウト

# アーカイブページ生成 (カスタム実装が必要)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# デフォルト設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "scripthropus"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# メニュー設定
header_pages:
  - about.md
  - categories.md

# Google Analytics (必要に応じて)
# google_analytics: UA-NNNNNNNN-N